# Serenity Configuration
serenity.project.name=saucedemo
serenity.test.root=com.saucedemo.saucedemo

# Screenshots - Granular configuration
serenity.take.screenshots.for.tasks=BEFORE_AND_AFTER_EACH_STEP
serenity.take.screenshots.for.interactions=FOR_FAILURES
serenity.take.screenshots.for.questions=AFTER_EACH_STEP

# Console
serenity.console.colors=true

# Custom Report Fields
report.customfields.user=Analista Automatizador
report.customfields.environment=Laboratorio
report.customfields.ApplicationVersion=1.0
report.customfields.order=ApplicationVersion,environment,user

# Reporting
serenity.report.show.manual.tests=false
serenity.report.show.releases=false
serenity.compress.filenames=true

# REST API
restapi.baseurl=https://saucedemo.com

# Logging
serenity.logging=VERBOSE
serenity.verbose.steps=false

# Timeouts (in milliseconds)
webdriver.timeouts.implicitlywait=2000
serenity.timeout=10000

# Parallel execution
serenity.batch.count=1
serenity.batch.number=1

# Test execution
serenity.restart.browser.for.each=scenario
